apiVersion: v1
kind: Service
metadata:
  name: rangersapp-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /
spec:
  type: LoadBalancer
  selector:
    app: rangersapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
